/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PackagesCreateRouteImport } from './routes/packages/create'
import { Route as PackagesIdRouteImport } from './routes/packages/$id'
import { Route as PackagesIdEditRouteImport } from './routes/packages/$id/edit'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesCreateRoute = PackagesCreateRouteImport.update({
  id: '/packages/create',
  path: '/packages/create',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesIdRoute = PackagesIdRouteImport.update({
  id: '/packages/$id',
  path: '/packages/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesIdEditRoute = PackagesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PackagesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/packages/$id': typeof PackagesIdRouteWithChildren
  '/packages/create': typeof PackagesCreateRoute
  '/packages/$id/edit': typeof PackagesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/packages/$id': typeof PackagesIdRouteWithChildren
  '/packages/create': typeof PackagesCreateRoute
  '/packages/$id/edit': typeof PackagesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/packages/$id': typeof PackagesIdRouteWithChildren
  '/packages/create': typeof PackagesCreateRoute
  '/packages/$id/edit': typeof PackagesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/profile'
    | '/packages/$id'
    | '/packages/create'
    | '/packages/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/profile'
    | '/packages/$id'
    | '/packages/create'
    | '/packages/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/profile'
    | '/packages/$id'
    | '/packages/create'
    | '/packages/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ProfileRoute: typeof ProfileRoute
  PackagesIdRoute: typeof PackagesIdRouteWithChildren
  PackagesCreateRoute: typeof PackagesCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/create': {
      id: '/packages/create'
      path: '/packages/create'
      fullPath: '/packages/create'
      preLoaderRoute: typeof PackagesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/$id': {
      id: '/packages/$id'
      path: '/packages/$id'
      fullPath: '/packages/$id'
      preLoaderRoute: typeof PackagesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/$id/edit': {
      id: '/packages/$id/edit'
      path: '/edit'
      fullPath: '/packages/$id/edit'
      preLoaderRoute: typeof PackagesIdEditRouteImport
      parentRoute: typeof PackagesIdRoute
    }
  }
}

interface PackagesIdRouteChildren {
  PackagesIdEditRoute: typeof PackagesIdEditRoute
}

const PackagesIdRouteChildren: PackagesIdRouteChildren = {
  PackagesIdEditRoute: PackagesIdEditRoute,
}

const PackagesIdRouteWithChildren = PackagesIdRoute._addFileChildren(
  PackagesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ProfileRoute: ProfileRoute,
  PackagesIdRoute: PackagesIdRouteWithChildren,
  PackagesCreateRoute: PackagesCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
